# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'locker_api_app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for locker_api_app
  pod 'Alamofire'
  pod 'SwiftyJSON'
  target 'locker_api_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
